---
- hosts: all
  become: true

  tasks:
    - name: Install web server
      package:
        name: "{{ 'apache2' if ansible_facts['os_family'] == 'Debian' else 'httpd' }}"
        state: present

    - name: Ensure web server is running
      service:
        name: "{{ 'apache2' if ansible_facts['os_family'] == 'Debian' else 'httpd' }}"
        state: started
        enabled: yes
    - name: Copy file with owner and permissions
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'

